# $Id: Makefile.rules,v 1.4 2003-08-19 12:31:41 raz Exp $

CC=g++
CFLAGS=-DOMIT_QUANTIFY_CALLS -g -Wall -DSIG_HANDLER_HAS_ONE_ARG=1 -DSHUT_UP_ABOUT_STATEMENT_WITH_NO_EFFECT_IN_DYNAMIC_ARRAY_CREATION -Wno-deprecated

BASEDIR=/home/raz/local

INCS=-I$(BASEDIR)/include/omega -I.
LIBS=-L$(BASEDIR)/lib
LIB=-lcode_gen -lomega -lm

GHC=ghc
